name: bai
channels:
  - pytorch
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - blas=1.0=mkl
  - bleach=3.2.3=pyhd3eb1b0_0
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2021.1.19=h06a4308_0
  - cairo=1.14.12=h8948797_3
  - certifi=2020.6.20=pyhd3eb1b0_3
  - cloudpickle=1.6.0=py_0
  - cudatoolkit=10.2.89=hfd86e86_1
  - cycler=0.10.0=py35hc4d5149_0
  - dask-core=2.6.0=py_0
  - dbus=1.13.18=hb2f20db_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.2.3=py35_2
  - expat=2.2.10=he6710b0_2
  - ffmpeg=4.0=hcdf2ecd_0
  - fontconfig=2.13.0=h9420a91_0
  - freeglut=3.0.0=hf484d3e_5
  - freetype=2.10.4=h5ab3b9f_0
  - glib=2.63.1=h5a9c865_0
  - graphite2=1.3.14=h23475e2_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - harfbuzz=1.8.8=hffaf4a1_0
  - hdf5=1.10.2=hba1933b_1
  - icu=58.2=he6710b0_3
  - imageio=2.9.0=py_0
  - intel-openmp=2019.4=243
  - ipykernel=4.10.0=py35_0
  - ipython=5.8.0=py35_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.4.1=py35_0
  - jasper=2.0.14=h07fcdf6_1
  - jinja2=2.11.2=pyhd3eb1b0_0
  - jpeg=9b=h024ee3a_2
  - jsonschema=2.6.0=py35h4395190_0
  - jupyter=1.0.0=py35_7
  - jupyter_client=5.3.3=py_0
  - jupyter_console=5.2.0=py35h4044a63_1
  - jupyter_core=4.5.0=py_0
  - kiwisolver=1.0.1=py35hf484d3e_0
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.2.1=hf484d3e_1007
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libglu=9.0.0=hf484d3e_1
  - libopencv=3.4.2=hb342d67_1
  - libopus=1.3.1=h7b6447c_0
  - libpng=1.6.37=hbc83047_0
  - libsodium=1.0.16=h1bed415_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - libuuid=1.0.3=h1bed415_2
  - libvpx=1.7.0=h439df22_0
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.10=hb55368b_3
  - lz4-c=1.9.3=h2531618_0
  - markupsafe=1.0=py35h14c3975_1
  - matplotlib=3.0.0=py35h5429711_0
  - mistune=0.8.3=py35h14c3975_1
  - mkl=2018.0.3=1
  - nbconvert=5.5.0=py_0
  - nbformat=5.1.2=pyhd3eb1b0_1
  - ncurses=6.2=he6710b0_1
  - networkx=2.4=py_1
  - ninja=1.8.2=py35h6bb024c_1
  - notebook=5.6.0=py35_0
  - numpy=1.14.2=py35hdbf6ddf_0
  - olefile=0.46=py35_0
  - opencv=3.4.2=py35h6fd60c2_1
  - openssl=1.0.2u=h7b6447c_0
  - packaging=20.8=pyhd3eb1b0_0
  - pandoc=2.11=hb0f4dca_0
  - pandocfilters=1.4.2=py35_1
  - pcre=8.44=he6710b0_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=5.2.0=py35heded4f4_0
  - pip=10.0.1=py35_0
  - pixman=0.40.0=h7b6447c_0
  - prometheus_client=0.9.0=pyhd3eb1b0_0
  - prompt_toolkit=1.0.15=py35hc09de7a_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - py-opencv=3.4.2=py35hb342d67_1
  - pygments=2.7.4=pyhd3eb1b0_0
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pyqt=5.9.2=py35h05f1152_2
  - python=3.5.6=hc3d631a_0
  - python-dateutil=2.8.1=py_0
  - pytorch=1.5.1=py3.5_cuda10.2.89_cudnn7.6.5_0
  - pytz=2020.5=pyhd3eb1b0_0
  - pywavelets=1.0.0=py35hdd07704_0
  - pyzmq=17.1.2=py35h14c3975_0
  - qt=5.9.6=h8703b6f_2
  - qtconsole=4.7.7=py_0
  - qtpy=1.9.0=py_0
  - readline=7.0=h7b6447c_5
  - scikit-image=0.14.0=py35hf484d3e_1
  - scipy=1.1.0=py35hd20e5f9_0
  - send2trash=1.5.0=pyhd3eb1b0_1
  - setuptools=40.2.0=py35_0
  - simplegeneric=0.8.1=py35_2
  - sip=4.19.8=py35hf484d3e_0
  - six=1.15.0=pyhd3eb1b0_0
  - sqlite=3.33.0=h62c20be_0
  - terminado=0.8.1=py35_1
  - testpath=0.4.4=py_0
  - tk=8.6.10=hbc83047_0
  - toolz=0.11.1=pyhd3eb1b0_0
  - torchaudio=0.5.1=py35
  - torchvision=0.6.1=py35_cu102
  - tornado=5.1.1=py35h7b6447c_0
  - traitlets=4.3.2=py35ha522a97_0
  - wcwidth=0.2.5=py_0
  - webencodings=0.5.1=py35_1
  - wheel=0.36.2=pyhd3eb1b0_0
  - widgetsnbextension=3.4.1=py35_0
  - xz=5.2.5=h7b6447c_0
  - zeromq=4.2.5=hf484d3e_1
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h9ceee32_0
  - pip:
    - chardet==4.0.0
    - click==7.1.2
    - configparser==4.0.2
    - docker-pycreds==0.4.0
    - gitdb==4.0.5
    - gitpython==3.1.12
    - idna==2.10
    - pathtools==0.1.2
    - promise==2.3
    - protobuf==3.14.0
    - psutil==5.8.0
    - pyyaml==5.3.1
    - requests==2.25.1
    - sentry-sdk==0.19.5
    - shortuuid==1.0.1
    - smmap==3.0.5
    - subprocess32==3.5.4
    - tqdm==4.56.0
    - urllib3==1.26.3
    - wandb==0.10.15
    - watchdog==0.10.4
prefix: /om/user/smadan/miniconda3/envs/bai

